language: node_js
sudo: false
node_js:
- '7'
branches:
  only:
  - master
env:
  global:
    - secure: "Ju4eC0wN217KB9m+LgwkwoZ27S36uQJZB+Kig3rmRraxenQbw15dIFc01f8jcJji5QbdaZN+JvwFlhNepGqAcOJnM9tCzB980Use04sKL9V6BBCUE5ucqcwf6eIa7AOIsENeac24vkq5YdzsaRw1tVJH8jzgvwU4Sbr2lXKsGB5JpJBKl0LpqZABTGedaZTx4zo9JESKee9Zqo4KYOrHIT1u0NEj3w1FXLtTlFF+4ukowUdmq2LCW2fp4wibpuxklLYUS64mAPTVRpiLWEzNOkBq/VXn52D45wRZmMoUWLabqAxJwdKhwlDS/kv9g3xP3z0kqfEJXl3xK2mQY+5Jnb87xG2azK4Le+cTckEkIYuXyhIYSBiNODJ2CD6cvyrcdRNtffjmQwUiuAkxbQRdOGOWyCzMjtTZRfeP22YtW0B12Uv/Sn/GIs2vrbY2nveOmXu6GrIEX/HXx8HuqY9l4dOtBru8p2RGN3as4rmAur7XQdpGQkxPONdHAXdzVBxch6JwDTehsSdG0Rb9YjUfg2fdMda3/tGbnPKAh5NTeP9iSpuwWioWVppnJAvJ4+LH4KlkdmWgdRsAtRvJGn+JxwIOzvsCcqD3wAIpXxjokgpyQqHWSlTFBmgdzfjD8fVIlNFbxqAGcQRRAtX37YwkHVloPuX8jvU9PJX2+CTLp9o="
    - secure: "jxQkJC689oySlE/FckOrEmWZZIixZf/CHEzr0J6CUOYJH8SaIa63/1VWHybkohYfWYcl6dwrAKSU+6gaLQ/bet66qP117V2HCGN+r56RPIALQbMt+cMuqaeNP/nn5hDEfEB2+GJcLAvBVrEiZ8UxWmAYiT9FsjGTp6Q8d+cUFGfVXnfT1r5MWbn4d2DpUriqjxvFpqfC+dnt3ZByKb6xxY6yJ4snsseyihfCQy2Lnsu5Rb6N4WBdvvBZvXCxnuxzWEceolZymcDEkSxSgVuV+ejPvaJogyF8jrV9ahiY4qT8gwX8RTWqzP7mXd0Id3iRdCKEjvHxY82OaIM7skBnw4adl/JZpCQ8iSva0khSE6xPAFlJdk9dY7M72+pf77P4ZKTTnjQcnafDD5x7vGDgX/XkiEYUcDGl93RKDce35D/JrtlYTRv4HGFS4HnKYSmKI+vpkQo4pxLOUQXFhGul5hkGTiDaaAuulZ9ink+yYDQkG/ZsWHM8vhov1lanBVULUxBoCb+wm1+EuNVlrG4q4bpQS+L5bj3tOn3mw9jlyMWfDfa9v3rM6vG0zic6WrZ2BNYguQWvICJvFDXNo6EgtfxIzGaeOq7KGXcujnkaZAsNPmgj6hGFVC62NjrDkv1b84VUydWner0qtHvaqoCJradgPL2lPCLnprLZ6xMBBbA="
    - secure: "Wvv4KK0iXYPIvwH6HE0KlLL4xb6DvemTybYuez0wwVwLBvVFR9XiLbYp7isS8u6BDIQsJ4fpafrQ0h5xbA+EQrcJSGBPa3oNfUthvv6NXPpZnKtoq1T1cdb66QFfZtdT+uyenQWzb/LP4oyE0wPi0MBGA6r9rvYjRcVWXA45U1tE/3MIm40fnOfA4sZNo/dmpbmpug+ID+F7k8qLO8Lx7BndbQhId5hZWU8xwEdY/q9JAWfm+iok6NUOXXA2932ZyXXzYhADJHmoFJbGigEu/2XkfO/UD+MZ/UYe6npvQMZy0hhV6mJzZBkoFQrkw0ases46ML9tqZtvTIze7Df3SBM+g9RFb/Mmi+oqWsndy3UqC+ZssimANqQ4Woy59PiILJhof3WPws+cuneUtHYi6Dp5FK4rZkfu2gQwXBwBAVkR7myU7OUKGKhFrc1o6z56iRG8p6YaVJQvmugQxpSKXziETT9s9Vfs17UBygyhGzIAspkvgdru02ZV8I6aG7K4vob4ayy+5uRVcYSl+lXhpKgvXYK7YVzgLOeQlfXNKT4MnqSt3/2obIYVfOlLt7tPt/klFs9CviLV2ptfDaVJiCrmpcimMiP/ZCJRevZjzgZ563N35xB+HJlaqhpyVO9IUTyyPb4hSXaR/+Z2iP6keXd5/qEqvSTs0MQcQiVA/1U="
before_script:
  - npm install
script:
  - npm run webpack
after_success:
  - mkdir archive
  - mv * archive
  - tar -czf package.tgz archive
  - echo $DEPLOY_USER@$DEPLOY_HOST
  - cat $DEPLOY_PATH/deploy.sh
#  - ssh $DEPLOY_USER@$DEPLOY_HOST